version: "3"

services:
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile.multi
    ports:
      - 8080:8080
    environment:
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
      - SERVER_PORT=8080
    depends_on:
      - mysqlserver
  mysqlserver:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: