name: Java CI Matrix Build

on: [push, pull_request]

jobs:
  build:
    runs_on: ubuntu-latest

  strategy:
    matrix:
      java: [8, 11, 17]

  name: Build with Java ${{ matrix.java }}

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Build with Gradle
      run: ./gradlew build
