name: Deploy PetClinic

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment
        run: echo "Selected environment is ${{ github.event.inputs.environment }}"
